name: 'Code Tests'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pester
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Force;
        shell: pwsh
      
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: BuildName
          file: cov.xml
